export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const ADD_COMMENT = "ADD_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const TOGGLE_TASK_COMPLETION = "TOGGLE_TASK_COMPLETION";
export const UPDATE_TASK_TIME = "UPDATE_TASK_TIME";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASK_ADDED = "TASK_ADDED";
export const TASK_EDITED = "TASK_EDITED";
export const TASK_DELETED = "TASK_DELETED";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_DELETED = "COMMENT_DELETED";
